; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
; This explicitly instructs the compiler to force the standard Serial command to use the native on-chip USB interface on boot
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
;    -DCONFIG_BT_NIMBLE_LOG_LEVEL=4
;    -DCORE_DEBUG_LEVEL=5
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1

; Skip analysis of external libraries and framework packages
check_skip_lib = yes

; Add flags to ignore preprocessor expansion errors in system headers
check_flags =
  cppcheck: --suppress=preprocessorErrorDirective --inline-suppr

# upload_port = /dev/tty.usbmodem11201
# monitor_port = /dev/tty.usbmodem11201